# Generated by Django 4.1.7 on 2026-02-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
